#!/bin/bash -e

echo "Copying text files to useful locations from $PWD.."

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

install_config_files() {
  for rc in .*rc .tmux.conf; do
    cp -v $BASE/$rc $HOME/$rc
  done

  mkdir -p $HOME/.vim/colors
  cp -v $BASE/rollout.vim $HOME/.vim/colors/rollout.vim
}

configure_git() {
  echo 'Configuring git..'
  git config --global --replace-all core.editor 'vim'
  git config --global --replace-all core.autocrlf false
  git config --global --replace-all alias.aa 'add --all'
  git config --global --replace-all alias.br 'branch --sort=committerdate'
  git config --global --replace-all alias.st 'status'
  git config --global --replace-all alias.count 'shortlog -sn'
  git config --global --replace-all alias.ff 'pull --ff-only'
  git config --global --replace-all alias.co 'checkout'
  git config --global --replace-all alias.ci 'commit --verbose'
  git config --global --replace-all alias.di 'diff'
  git config --global --replace-all alias.dc 'diff --cached'
  git config --global --replace-all alias.dd 'diff --stat origin/develop HEAD'
  git config --global --replace-all alias.list 'config --global --list'
  git config --global --replace-all alias.amend 'commit --amend'
  git config --global --replace-all alias.ffa 'fetch --all && git rebase origin/master'
  git config --global --replace-all alias.push-new 'push -u origin HEAD'
  git config --global --replace-all alias.ra "log --abbrev-commit --pretty=format:'%<(7)%C(yellow)%h %Cgreen%<(15)%cr%C(bold cyan)%<(17)<%an>%C(red)%d %Creset %s'"
}

is_0() {
  if [ "$1" = "0" ]; then
    echo 'true'
    return
  fi
  echo 'false'
}

exists() {
  echo -n "Is $1 installed? "
  [ $(command -v "$1") ] && echo 'true' || echo 'false'
}

if command -v selecta &> /dev/null; then
  echo 'selecta is already installed'
else
  echo 'selecta could not be found, installing to ~/.local/bin/selecta'
  mkdir -p ~/.local/bin
  curl https://raw.githubusercontent.com/garybernhardt/selecta/master/selecta -o ~/.local/bin/selecta
  chmod +x ~/.local/bin/selecta
fi

compile_vim() {
  # not complete.. just jotting down the compilation flags for now.
  ./configure --with-x --with-features=huge --enable-pythoninterp # --enable-gui
}

set_colours() {
  echo 'set_colours not implemented yet, skipping..'
  # ! special
  # *.foreground:   #f7fafc
  # *.background:   #1a202c
  # *.cursorColor:  #f7fafc

  # ! black
  # *.color0:       #2d3748
  # *.color8:       #718096

  # ! red
  # *.color1:       #f56565
  # *.color9:       #feb2b2

  # ! green
  # *.color2:       #c6f6d5
  # *.color10:      #f0fff4

  # ! yellow
  # *.color3:       #faf089
  # *.color11:      #fefcbf

  # ! blue
  # *.color4:       #bee3f8
  # *.color12:      #ebfff8

  # ! magenta
  # *.color5:       #ed64a6
  # *.color13:      #fbb6ce

  # ! cyan
  # *.color6:       #4fd1c5
  # *.color14:      #b2f5ea

  # ! white
  # *.color7:       #f7fafc
  # *.color15:      #ffffff
}
check_external_commands() {
  echo 'Checking for external dependencies..'

  # N.B in the event that either of these is missing AND your package manager
  # can't install recent versions of this, they are not too time consuming to
  # compile from source. Tmux relies on libevent, you'll also probably need
  # libtool autoconf make and the usual suspects.

  # Vim in particular checks for two X11 headers, Intrinsic.h and X11.h -
  # Intrinsic isn't always in the same dev package (e.g in rhel, it's in
  # libXt-devel
  is_vim_8=$(vim --version | grep IMproved | grep -q "\s8"; is_0 $?)
  echo "Is vim version 8+? $is_vim_8"

  is_tmux_2=$(tmux -V| grep -q "\s\(2\|3\)"; is_0 $?)
  echo "Is tmux version 2+? $is_tmux_2"

  exists git
  exists xmllint
  exists npm
  exists node
  exists ruby
  exists selecta # fuzzy searching utility
  exists ts-node
  exists wget
  exists curl
  exists bc # required for backward compatible tmux code
  exists fd # better version of find
  exists rg # ripgrep is a better version of grep
}

install_config_files
configure_git
set_colours
check_external_commands
mkdir -p ~/.local/bin && cp ./ns ~/.local/bin
