#!/bin/bash -e

echo "Copying text files to useful locations from $PWD.."

cd $(dirname $BASH_SOURCE)
BASE=$(pwd)

install_config_files() {
  for rc in .*rc .tmux.conf; do
    cp -v $BASE/$rc $HOME/$rc
  done

  mkdir -p $HOME/.vim/colors
  cp -v $BASE/rollout.vim $HOME/.vim/colors/rollout.vim
}

configure_git() {
  echo 'Configuring git..'
  git config --global --replace-all core.editor 'vim'
  git config --global --replace-all core.autocrlf false
  git config --global --replace-all alias.aa 'add --all'
  git config --global --replace-all alias.br 'branch --sort=committerdate'
  git config --global --replace-all alias.st 'status'
  git config --global --replace-all alias.count 'shortlog -sn'
  git config --global --replace-all alias.ff 'pull --ff-only'
  git config --global --replace-all alias.co 'checkout'
  git config --global --replace-all alias.ci 'commit --verbose'
  git config --global --replace-all alias.di 'diff'
  git config --global --replace-all alias.dc 'diff --cached'
  git config --global --replace-all alias.dd 'diff --stat origin/develop HEAD'
  git config --global --replace-all alias.list 'config --global --list'
  git config --global --replace-all alias.amend 'commit --amend'
  git config --global --replace-all alias.ffa 'fetch --all && git rebase origin/master'
  git config --global --replace-all alias.push-new 'push -u origin HEAD'
  git config --global --replace-all alias.ra "log --abbrev-commit --pretty=format:'%<(7)%C(yellow)%h %Cgreen%<(15)%cr%C(bold cyan)%<(17)<%an>%C(red)%d %Creset %s'"
}

is_0() {
  if $1; then
    echo 'true'
    return
  fi
  echo 'false'
}

exists() {
  echo -n "Is $1 installed? "
  [ $(command -v "$1") ] && echo 'true' || echo 'false'
}

if command -v selecta &> /dev/null; then
  echo 'selecta is already installed'
else
  echo 'selecta could not be found, installing to ~/.local/bin/selecta'
  mkdir -p ~/.local/bin
  curl https://raw.githubusercontent.com/garybernhardt/selecta/master/selecta -o ~/.local/bin/selecta
  chmod +x ~/.local/bin/selecta
fi

check_external_commands() {
  echo 'Checking for external dependencies..'

  is_vim_8=$(vim --version | grep IMproved | grep -q "\s8" | is_0)
  echo "Is vim version 8+? $is_vim_8"

  is_tmux_2=$(tmux -V| grep "\s\(2\|3\)" | is_0)
  echo "Is tmux version 2+? $is_tmux_2"

  exists git
  exists xmllint
  exists npm
  exists node
  exists ruby
  exists selecta # fuzzy searching utility
  exists ts-node
  exists wget
  exists curl
}

install_config_files
configure_git
check_external_commands
